package com.createenigma.structure;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import com.createenigma.CreateEnigma;
import com.createenigma.registry.CEBlocks;
import com.mojang.logging.LogUtils;

import org.slf4j.Logger;

import net.minecraft.core.BlockPos;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.Vec3i;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.NbtAccounter;
import net.minecraft.nbt.NbtIo;
import net.minecraft.nbt.NbtUtils;
import net.minecraft.nbt.Tag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;

/**
 * The Enigma machine's shape, read once from the structure template this mod ships.
 *
 * <p>The template is generated by {@code tools/PrepareEnigmaStructure.java} from Create's Ponder
 * capture, and lives at {@code data/create_enigma/structure/mojang_enigma.nbt}. The same file is
 * what {@code /place template create_enigma:mojang_enigma} places, so the shape that gets built
 * and the shape that gets recognised provably come from one source.
 *
 * <p><b>Loaded from the classpath, not the datapack resource manager.</b> That keeps the check
 * independent of resource reloads and of datapacks that might override the template - at the cost
 * of not honouring such an override. If the template ever becomes datapack-tunable, this is the
 * place to change.
 */
public final class EnigmaStructure {

    private static final Logger LOGGER = LogUtils.getLogger();

    /**
     * The template's id: exactly what {@code /place template} takes and what its tab completion
     * lists. The classpath location below is derived from it, so the id the command resolves and
     * the file this mod reads can never drift apart.
     */
    public static final ResourceLocation TEMPLATE_ID =
            ResourceLocation.fromNamespaceAndPath(CreateEnigma.MOD_ID, "mojang_enigma");

    private static final String RESOURCE =
            "/data/" + TEMPLATE_ID.getNamespace() + "/structure/" + TEMPLATE_ID.getPath() + ".nbt";

    private static EnigmaStructure instance;
    private static boolean loadAttempted;

    /** One block of the machine, at its offset from the template's own corner. */
    public record Entry(BlockPos offset, BlockState state) {}

    private final Vec3i size;
    private final List<Entry> entries;
    private final BlockPos coreOffset;

    private EnigmaStructure(Vec3i size, List<Entry> entries, BlockPos coreOffset) {
        this.size = size;
        this.entries = entries;
        this.coreOffset = coreOffset;
    }

    /** The template's dimensions. */
    public Vec3i size() {
        return size;
    }

    /** Every non-air block of the machine, in template coordinates. */
    public List<Entry> entries() {
        return entries;
    }

    /** Where this mod's core block sits inside the template. */
    public BlockPos coreOffset() {
        return coreOffset;
    }

    /**
     * Turns the world position of a core block into the template's own origin, so that
     * {@code origin.offset(entry.offset())} addresses the world.
     */
    public BlockPos originFor(BlockPos corePos) {
        return corePos.subtract(coreOffset);
    }

    /** Loads on first use. Returns null - and logs once - if the template cannot be read. */
    public static EnigmaStructure get() {
        synchronized (EnigmaStructure.class) {
            if (!loadAttempted) {
                loadAttempted = true;
                instance = load();
            }
            return instance;
        }
    }

    private static EnigmaStructure load() {
        try (InputStream in = EnigmaStructure.class.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                LOGGER.error("Enigma structure template is missing from the jar: {}", RESOURCE);
                return null;
            }

            CompoundTag root = NbtIo.readCompressed(in, NbtAccounter.unlimitedHeap());

            ListTag sizeTag = root.getList("size", Tag.TAG_INT);
            Vec3i size = new Vec3i(sizeTag.getInt(0), sizeTag.getInt(1), sizeTag.getInt(2));

            HolderGetter<Block> blockLookup = BuiltInRegistries.BLOCK.asLookup();

            ListTag paletteTag = root.getList("palette", Tag.TAG_COMPOUND);
            List<BlockState> palette = new ArrayList<>(paletteTag.size());
            for (int i = 0; i < paletteTag.size(); i++) {
                palette.add(NbtUtils.readBlockState(blockLookup, paletteTag.getCompound(i)));
            }

            ListTag blocksTag = root.getList("blocks", Tag.TAG_COMPOUND);
            List<Entry> entries = new ArrayList<>(blocksTag.size());
            BlockPos coreOffset = null;

            for (int i = 0; i < blocksTag.size(); i++) {
                CompoundTag blockTag = blocksTag.getCompound(i);
                ListTag posTag = blockTag.getList("pos", Tag.TAG_INT);
                BlockPos offset = new BlockPos(posTag.getInt(0), posTag.getInt(1), posTag.getInt(2));
                BlockState state = palette.get(blockTag.getInt("state"));

                if (state.isAir()) {
                    continue;
                }
                entries.add(new Entry(offset, state));
                if (state.is(CEBlocks.ENIGMA_CORE.get())) {
                    coreOffset = offset;
                }
            }

            if (coreOffset == null) {
                LOGGER.error("Enigma structure template contains no {} block", CEBlocks.ENIGMA_CORE.getId());
                return null;
            }

            LOGGER.info("Enigma structure loaded: {} blocks, size {}, core at {}",
                    entries.size(), size, coreOffset);
            return new EnigmaStructure(size, List.copyOf(entries), coreOffset);
        } catch (Exception e) {
            LOGGER.error("Failed to read the Enigma structure template", e);
            return null;
        }
    }
}
